import type { Metadata } from "next";
import Head from "next/head";
import { GlobalProviders } from "./context/GlobalProviders";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <title>DS AutoRouting</title>
      </Head>
      <GlobalProviders>{children}</GlobalProviders>
    </>
  );
}
